CREATE DATABASE IF NOT EXISTS groupdb
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE groupdb;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('user','admin') NOT NULL DEFAULT 'user',
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS groups (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  groupName VARCHAR(255) NOT NULL UNIQUE,
  courseName VARCHAR(255) NOT NULL,
  courseCode VARCHAR(100) NOT NULL,
  faculty VARCHAR(255) NOT NULL,
  description VARCHAR(500) NOT NULL,
  meetingLocation VARCHAR(255) NOT NULL,
  meetingType ENUM('physical','online','hybrid') NOT NULL DEFAULT 'physical',
  leaderId INT UNSIGNED NOT NULL,
  isActive TINYINT(1) NOT NULL DEFAULT 1,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (leaderId) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sessions (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  groupId INT UNSIGNED NOT NULL,
  sessionDate DATETIME NOT NULL,
  topic VARCHAR(255) NOT NULL,
  location VARCHAR(255),
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES groups(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS group_members (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  groupId INT UNSIGNED NOT NULL,
  userId INT UNSIGNED NOT NULL,
  joinedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (groupId) REFERENCES groups(id) ON DELETE CASCADE,
  FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_group_member (groupId, userId)
) ENGINE=InnoDB;